spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ltravel_db?useSSL=false&serverTimezone=UTC}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: XXX
    password: XXX
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update