spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    url: ${MYSQL_PUBLIC_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQLUSER:root}
    password: ${MYSQL_ROOT_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  ai:
    openai:
      base-url: https://api.deepseek.com
      api-key: sk-2a3c0bee5d534c3cb93a21a6ff32ed80
      chat:
        options:
          model: deepseek-chat